namespace ScreenGuardAI.Models;

public class UserProfile
{
    public string FullName { get; set; } = string.Empty;
    public string CurrentRole { get; set; } = string.Empty;
    public string YearsOfExperience { get; set; } = string.Empty;
    public string TargetRole { get; set; } = string.Empty;
    public string TechStack { get; set; } = string.Empty;
    public string KeyProjects { get; set; } = string.Empty;
    public string Education { get; set; } = string.Empty;
    public string Strengths { get; set; } = string.Empty;
    public string WorkStyle { get; set; } = string.Empty;
    public string AdditionalNotes { get; set; } = string.Empty;

    /// <summary>
    /// Generates a context string for AI prompts based on the profile.
    /// </summary>
    public string ToPromptContext()
    {
        var parts = new List<string>();

        if (!string.IsNullOrWhiteSpace(FullName))
            parts.Add($"Name: {FullName}");
        if (!string.IsNullOrWhiteSpace(CurrentRole))
            parts.Add($"Current role: {CurrentRole}");
        if (!string.IsNullOrWhiteSpace(YearsOfExperience))
            parts.Add($"Experience: {YearsOfExperience} years");
        if (!string.IsNullOrWhiteSpace(TargetRole))
            parts.Add($"Applying for: {TargetRole}");
        if (!string.IsNullOrWhiteSpace(TechStack))
            parts.Add($"Tech stack: {TechStack}");
        if (!string.IsNullOrWhiteSpace(KeyProjects))
            parts.Add($"Key projects/achievements: {KeyProjects}");
        if (!string.IsNullOrWhiteSpace(Education))
            parts.Add($"Education: {Education}");
        if (!string.IsNullOrWhiteSpace(Strengths))
            parts.Add($"Key strengths: {Strengths}");
        if (!string.IsNullOrWhiteSpace(WorkStyle))
            parts.Add($"Work style: {WorkStyle}");
        if (!string.IsNullOrWhiteSpace(AdditionalNotes))
            parts.Add($"Additional info: {AdditionalNotes}");

        return parts.Count > 0
            ? string.Join("\n", parts)
            : string.Empty;
    }

    /// <summary>
    /// Exports the profile as a portable Markdown document.
    /// </summary>
    public string ToMarkdown()
    {
        return $"""
                # Interview Profile

                ## Personal Information
                - **Name:** {FullName}
                - **Current Role:** {CurrentRole}
                - **Years of Experience:** {YearsOfExperience}
                - **Target Role:** {TargetRole}

                ## Technical Skills
                {TechStack}

                ## Key Projects & Achievements
                {KeyProjects}

                ## Education
                {Education}

                ## Strengths
                {Strengths}

                ## Work Style & Approach
                {WorkStyle}

                ## Additional Notes
                {AdditionalNotes}

                ---
                *Generated by ScreenGuard AI - Interview Assistant*
                *This file can be imported on any device running ScreenGuard AI.*
                """;
    }

    /// <summary>
    /// Returns true if any meaningful profile data exists.
    /// </summary>
    public bool HasData()
    {
        return !string.IsNullOrWhiteSpace(FullName) ||
               !string.IsNullOrWhiteSpace(CurrentRole) ||
               !string.IsNullOrWhiteSpace(TechStack) ||
               !string.IsNullOrWhiteSpace(KeyProjects);
    }
}
